spring:
  h2:
    console:
      enabled: true
      path: /h2

#  datasource:
#    datasource-initializer-enabled: true
 #   hikari:
   #   driver-class-name: org.h2.Driver
    #  connection-timeout: 30000
     # idle-timeout: 600000
      #max-lifetime: 1800000
      #     maximum-pool-size: 20
      #     minimum-idle: 5
    #      auto-commit: true
    #    connection-test-query: SELECT 1
    #    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;
    #    username: sa
    #     password:
    #    driverClassName: org.h2.Driver
  #    poolName: HikariCP-Principal

  datasource:
    datasource-initializer-enabled: false
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/InazumaWiki?useUnicode=true&characterEncoding=utf8
    username: demo
    password: demo
    driverClassName: com.mysql.cj.jdbc.Driver
    poolName: HikariCP-Principal
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
  logging:
    level:
      org:
        springframework: WARN
      root: WARN